### PR TITLE
Add CloudTrail Advanced Event Selector

### LINKED ISSUE #54: Unable to use exclude_management_event_sources in event_selector
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
Unable to use exclude_management_event_sources in event_selector

## Expected Behavior
We should be able to use something like
  event_selector = [{
        exclude_management_event_sources = ["kms.amazonaws.com","rdsdata.amazonaws.com"]
        include_management_events        = true
        read_write_type                  = "WriteOnly"
        }
  ]

But looks like  exclude_management_event_sources is not implemented

Check https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#exclude_management_event_sources

### LINKED ISSUE #69: Add Support for the CloudTrail Advanced Event Selector
### Describe the Feature

Specify an advanced event selector for enabling data event logging

## References

- https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_PutEventSelectors.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail.html#advanced_event_selector

### Expected Behavior

Be able to configure an advanced event selector on a CloudTrail trail.

### Use Case

Optimise CloudTrail trail costs by enabling a deeper level of customization to the type of API request that the trail will capture. 

### Describe Ideal Solution

Add an `advanced_event_selector` variable following the pattern used for the `event_selector` variable.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by X-Guardian**
## what

Add support for the CloudTrail advanced event selector

Also bumps the example `cloudtrail_s3_bucket module` and Terraform versions to fix test errors.

By @Nuru:
- Add `exclude_management_event_sources`. Supersedes and closes #60. Closes #54.
- Update tests and test framework.
- Add `.editorconfg`.
- Fix `tflint` complaints.

## references

- closes #69 
- Supersedes and closes #63

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]
thanks @X-Guardian for the contribution, once the terratest past we should be good to go

**Comment by jamengual** [comment]
the test failed, can you check?

And take a look at this please:

 https://docs.cloudposse.com/reference/best-practices/terraform-best-practices/#use-objects-with-optional-fields-for-complex-inputs

and this: https://docs.cloudposse.com/reference/best-practices/terraform-best-practices/#prefer-a-single-object-over-multiple-simple-inputs-for-related-configuration

it might be better to move it to a single object.

**Comment by X-Guardian** [comment]
Looks like the test framework is using a very old version of Terraform, so I have bumped the Terraform version in the example.

I have only added a single object...

**Comment by X-Guardian** [comment]
The successful running of the tests is blocked by https://github.com/cloudposse/terraform-aws-cloudtrail-s3-bucket/issues/90

**Review by Nuru — APPROVED** [review]

**Pull request merged**
