### PR TITLE
add s3_key_prefix variable

### PR DESCRIPTION
**Pull request by niraj8**
## what
* Add `s3_key_prefix` variable

## why
* To allow users of this module to be able to store Cloudtrail logs in s3 bucket with a chosen prefix

### CODE REVIEW

**Comment by vzanlnx** [comment]
Hello, I'm interested in having this option in the official module, any chances of merging  this? cc @Gowiem

**Comment by Gowiem** [comment]
@vzanlnx sorry -- This one ended up sitting and that looks to be on me. Let's get it moving along. 

@niraj8 your work got out of date. Would you mind pulling the latest from `master` (or rebasing), run `make init && make readme`, and then push the results?

**Comment by niraj8** [comment]
@Gowiem
Updated the PR.
I think the bridgecrew errors are due to default empty values for `kms_key_arn` & `cloud_watch_logs_group_arn`, not sure though.

Let me know if these need to be fixed.

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@niraj8 thanks! Released as [0.21.0](https://github.com/cloudposse/terraform-aws-cloudtrail/releases/tag/0.21.0) 👍 

cc @vzanlnx

**Pull request merged**
